export const FONT_OPTIONS = [
  { name: "기본 (Pretendard)", value: "sans-serif", category: "고딕" },
  { name: "Noto Sans KR", value: "'Noto Sans KR', sans-serif", category: "고딕" },
  { name: "나눔고딕 (Nanum Gothic)", value: "'Nanum Gothic', sans-serif", category: "고딕" },
  { name: "IBM Plex Sans KR", value: "'IBM Plex Sans KR', sans-serif", category: "고딕" },
  { name: "Gothic A1", value: "'Gothic A1', sans-serif", category: "고딕" },
  { name: "Do Hyeon (도현)", value: "'Do Hyeon', sans-serif", category: "고딕" },
  { name: "Jua (주아)", value: "'Jua', sans-serif", category: "고딕" },
  { name: "Black Han Sans", value: "'Black Han Sans', sans-serif", category: "고딕" },
  { name: "Noto Serif KR", value: "'Noto Serif KR', serif", category: "명조" },
  { name: "나눔명조 (Nanum Myeongjo)", value: "'Nanum Myeongjo', serif", category: "명조" },
  { name: "고운바탕 (Gowun Batang)", value: "'Gowun Batang', serif", category: "명조" },
  { name: "고운돋움 (Gowun Dodum)", value: "'Gowun Dodum', sans-serif", category: "명조" },
  { name: "송명 (Song Myung)", value: "'Song Myung', serif", category: "명조" },
  { name: "Hahmlet", value: "'Hahmlet', serif", category: "명조" },
  { name: "나눔 손글씨 펜 (Nanum Pen Script)", value: "'Nanum Pen Script', cursive", category: "손글씨" },
  { name: "나눔 손글씨 붓 (Nanum Brush Script)", value: "'Nanum Brush Script', cursive", category: "손글씨" },
  { name: "Stylish", value: "'Stylish', sans-serif", category: "손글씨" },
  { name: "Gaegu (개구)", value: "'Gaegu', cursive", category: "손글씨" },
  { name: "Hi Melody", value: "'Hi Melody', cursive", category: "손글씨" },
  { name: "Gamja Flower", value: "'Gamja Flower', cursive", category: "손글씨" },
  { name: "Single Day", value: "'Single Day', cursive", category: "손글씨" },
  { name: "Cormorant Garamond", value: "'Cormorant Garamond', serif", category: "영문" },
  { name: "Playfair Display", value: "'Playfair Display', serif", category: "영문" },
  { name: "Lora", value: "'Lora', serif", category: "영문" },
  { name: "Montserrat", value: "'Montserrat', sans-serif", category: "영문" },
  { name: "Inter", value: "'Inter', sans-serif", category: "영문" },
  { name: "Roboto", value: "'Roboto', sans-serif", category: "영문" },
  { name: "Open Sans", value: "'Open Sans', sans-serif", category: "영문" },
  { name: "Dancing Script", value: "'Dancing Script', cursive", category: "영문" },
  { name: "Great Vibes", value: "'Great Vibes', cursive", category: "영문" },
  { name: "Satisfy", value: "'Satisfy', cursive", category: "영문" },
  { name: "Libre Baskerville", value: "'Libre Baskerville', serif", category: "영문" },
  { name: "Crimson Text", value: "'Crimson Text', serif", category: "영문" },
];
